/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'renjithgr' at '1/17/16 12:21 AM' with Gradle 2.10
 *
 * @author renjithgr, @date 1/17/16 12:21 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
